name: Django Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run collectstatic
      run: |
        source venv/bin/activate
        python manage.py collectstatic --noinput


      
















# name: Deploy Django Static Files to S3

# on:
#   push:
#     branches:
#       - main  # Trigger on push to the main branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout the code
#       uses: actions/checkout@v2

#     - name: Configure AWS Credentials
#       uses: aws-actions/configure-aws-credentials@v2
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: eu-north-1

#     - name: Install AWS CLI
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y awscli

#     - name: Sync static files to S3
#       run: |
#         aws s3 sync ./staticfiles s3://deepsek --delete














      

    # - name: Set up Python environment
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: '3.8'  # Use the Python version you need

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    # - name: Run tests (optional)
    #   run: |
    #     python manage.py test  # Ensure your tests pass before deployment

    # - name: Build and collect static files
    #   run: |
    #     python manage.py collectstatic --noinput
        
    # - name: Deploy to AWS EC2
    #   env:
    #     EC2_HOST: ${{ secrets.EC2_HOST }}
    #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: ${{ secrets.AWS_REGION }}
    #   run: |
    #     echo "$SSH_PRIVATE_KEY" > private_key.pem
    #     chmod 600 private_key.pem

    #     # SSH into the EC2 instance and deploy
    #     ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$EC2_HOST << 'EOF'
    #       # Navigate to the Django app directory
    #       cd /path/to/your/django/app

    #       # Pull the latest code from GitHub (if using git to manage your app)
    #       git pull origin main

    #       # Install the required dependencies
    #       source /path/to/your/virtualenv/bin/activate
    #       pip install -r requirements.txt

    #       # Apply migrations
    #       python manage.py migrate

    #       # Restart the application (e.g., Gunicorn or Apache/Nginx)
    #       sudo systemctl restart gunicorn

    #       # Or restart Nginx (if needed)
    #       sudo systemctl restart nginx
    #     EOF
